C Frontend
circify/circ pull request #22
Opened 2021-10-20 22:30 UTC by edwjchen

Working C frontend supporting:
- one main function
- binary arithmetic 
- if-else stmts
- array select and store

Supports both integer and boolean types.

2021-10-22 01:00 UTC, alex-ozdemir requested changes
This is pretty close to a state where I'd be happy to merge it. There a few small issues noted inline, that should be fixed.

We may want to fix up the array notion at some point, but this is fine for now.

2021-10-22 04:03 UTC, edwjchen commented on examples/C/mpc/unit_tests/array_tests/2pc_array_sum.c
> +    int c[2][5][6];
ah! I think I was using this test to see how multiple dimensions arrays were initialized and I didn't remove `c`. Thanks for the catch!

2021-10-22 04:11 UTC, edwjchen commented on src/front/c/mod.rs
> +    fn get_bin_op(&self, op: BinaryOperator) -> fn(CTerm, CTerm) -> Result<CTerm, String> {
Haha :) I think you were the one who wrote this part first! Was very cool getting to read something like this!

2021-10-22 04:36 UTC, edwjchen commented on src/front/c/mod.rs
> +            if let Extension::Attribute(attr) = &node.node {
Hmm which parts exactly? It seems a little tricky with the call to self.gen_expr in the middle.

2022-01-19 22:25 UTC, alex-ozdemir requested changes
I looked at the C FE and your IR/circify changes quite closely. I only skimmed the ABY BE changes. I left a few comments inline.

One other question: 
* what is the `.pyc` file?

2022-01-19 22:25 UTC, alex-ozdemir commented on src/front/c/mod.rs
> +                }
This is a very common pattern. I'd consider adding a one-argument constructor.

2022-01-19 22:25 UTC, alex-ozdemir commented on src/front/c/mod.rs
> +    fn get_const_iters(&mut self, for_stmt: ForStatement) -> Option<ConstIteration> {
This function isn't quite right b/c the loop body could modify the iteration variable. We had a nice way to detect that in the Haskell compiler that would be a bit harder to replicate here. For now, why don't you write a comment noting the inaccuracy.

2022-01-19 22:25 UTC, alex-ozdemir commented on src/front/c/mod.rs
> +                name: init_name,
Is this field dead in the callee?

2022-01-19 22:25 UTC, alex-ozdemir commented on src/front/c/mod.rs
> +                                self.circ.assign_with_assertions(name, term, ty, PUBLIC_VIS);
I would actually do `unimplemented!()` here, unless you're going to test this support.

2022-01-19 22:25 UTC, alex-ozdemir commented on src/front/c/term.rs
> +    unimplemented!("Not implemented case in iUAC");
I'd move this into the `else`.

2022-01-19 22:25 UTC, alex-ozdemir commented on src/front/zokrates/mod.rs
> +
Remove this? Also, see [here](https://docs.rs/env_logger/latest/env_logger/index.html) for how to use the logging infrastructure. Quickstart: set `RUST_LOG=debug ` before running the binary.

2022-01-19 22:25 UTC, alex-ozdemir commented on third_party/ABY_templates/cpp_template.txt
> -	delete party;
Why this change?

2022-01-19 22:25 UTC, alex-ozdemir commented on src/ir/opt/binarize.rs
> +}
I'd recommend using `Iterator::fold` instead of recursion here. We build some *very* large n-ary terms, and don't want to blow the stack.

2022-01-19 22:25 UTC, alex-ozdemir commented on src/ir/opt/cfold.rs
> +                    (Udiv, _, Some(b)) if b.uint() == &Integer::from(0) => Some(c0.clone()),
Not quite. We're following SMT-LIB, which says this should be the maximum representable value:
> [[(bvudiv s t)]] := if bv2nat([[t]]) = 0
                       then λx:[0, m). 1
                       else nat2bv[m](bv2nat([[s]]) div bv2nat([[t]]))

See: https://smtlib.cs.uiowa.edu/theories-FixedSizeBitVectors.shtml or https://github.com/circify/circ/blob/master/src/ir/term/bv.rs#L38-L61

2022-01-19 22:25 UTC, alex-ozdemir commented on src/front/c/mod.rs
> +                    // println!("function: {:#?}", fn_def.node);
rm

2022-01-20 15:34 UTC, edwjchen commented
> * what is the `.pyc` file?

the `.pyc` was just a cache bytecode of the python test script. I adjusted the `make clean` command to remove them!

2022-01-20 18:16 UTC, alex-ozdemir approved these changes
Great!

2022-01-20 18:16 UTC, merged